
spring:
  application:
    name: "practice"
  datasource:
    url: jdbc:mysql://localhost:3306/db_practice?characterEncoding=utf8&serverTimezone=Asis/Seoul
    username: goodee
    password: goodee
    
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: org.shining.practice.user.dto
  configuration:
    map-underscore-to-camel-case: true